### ISSUE TITLE
怎么运行 go 程序的？

### ISSUE THREAD

**Issue by JackSinner** [honmaple/maple-file#13]
怎么运行 go 程序的？

**Comment by ltaoo** [comment]
我运行了这个项目，是把 go 编译成 lib 包，在 flutter 中通过  final lib = LibserverBind(ffi.DynamicLibrary.open(libname)); 引入的

**Comment by honmaple** [comment]
@JackSinner 主要用到了这两个 
- https://github.com/golang/mobile
- https://docs.flutter.dev/platform-integration/macos/c-interop
