### ISSUE TITLE
新增存储，看不到alist

### ISSUE THREAD

**Issue by xuconnery** [honmaple/maple-file#14]
只有如下几个选项 ，MacOS 12.6.3

<img width="319" alt="截屏2024-12-31 20 35 51" src="https://github.com/user-attachments/assets/63900adc-0d37-4c3e-88a9-7fdb36af56bc" />

**Comment by honmaple** [comment]
下载的版本不对，最新版应该是这个 https://github.com/honmaple/maple-file/releases/tag/v1.0.0-1
